apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: env
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: env
    spec:
      containers:
        - name: env
          image: ulamlabs/env
          ports:
            - containerPort: 80
          env:
            - name: ENV
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeNam